### ISSUE TITLE
Webhook nie wysyła powiadomienia

### ISSUE THREAD

**Issue by sc4rface97** [automater-pl/rest-api#1]
W związku z potrzebą zaimplementowania pewnego systemu, chciałem zastosować webhook, który udostępniacie (zamiast odpytywania API cyklicznie i filtrowania listy transakcji). Niestety, ale powiadomienie nie jest przesyłane na wskazany adres url. 

Czy system został zdeprecjonowany, czy macie jakiś wewnętrzny błąd?

**Comment by jkb32** [comment]
Problem mógł występować dla niektórych typów transakcji. **Zlokalizowaliśmy go i usunęliśmy** - wszystkie powiadomienia są juz wysyłane prawidłowo.
